name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure git identity
      run: |
        git config --global user.email "test@tuture.co"
        git config --global user.name "Tuture"

    - name: install dependencies and run test
      run: |
        yarn
        yarn lint
        yarn test
      env:
        CI: true
